### ISSUE TITLE
[Suggestion] why not look into reading from a file instead of using string input

### ISSUE THREAD

**Issue by farhaanbukhsh** [SRvSaha/dgplug_problems#1]

**Comment by SRvSaha** [comment]
Actually I know file handling but since it wasn't taught in DGPLUG so I did with strings. Anyways, the output is not correct and I figured out the correct output. Will update soon

**Comment by SRvSaha** [comment]
Ok, I've updated the codes. ADDED FILE HANDLING FOR INPUT
